name: "adolla_dev"

services:
  postgres:
    image: postgres
    ports:
     - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
     - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
