name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install and build binaries
        run: |
          npm install
          npm run build-binaries
      - name: Store binaries Mac
        uses: actions/upload-artifact@v2
        with:
          name: release-mac
          path: |
            index-macos
            views
            dist
            public
            package.json
      - name: Store binaries Window
        uses: actions/upload-artifact@v2
        with:
          name: release-windows
          path: |
            index-win.exe
            views
            dist
            public
            package.json
      - name: Store binaries Linux
        uses: actions/upload-artifact@v2
        with:
          name: release-linux
          path: |
            index-linux
            views
            dist
            public
            package.json
      #     path: output/test/code-coverage.html
